- .circleci/config.yml
- scripts/setup_circleci_checkout_api.sh
- test/server/api.json.test.js
Fix all CI issues and make the CI work again. 🐨
> Trying to fix the CI Build Failures

- renovate.json
Related to https://github.com/opencollective/opencollective/issues/4243
> Add centralized config to renovate

- src/graphql/schema.graphql
- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.js
Require API: https://github.com/opencollective/opencollective-api/pull/6509
> Implement flatten host fees

- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.js
and includeChildrenTransactions
> Support for include Incognito/Children Transactions

- docs/transactions.md
https://github.com/opencollective/opencollective-rest/blob/transactions-documentation/docs/transactions.md
> Add documentation for the transactions v2 endpoint

- src/server/controllers/account-transactions.js
This is only available for user with appropriate permissions.
> Add email for individuals

- docs/transactions.md
- src/server/controllers/account-transactions.js
Part of Resolve opencollective/opencollective#4660
Require https://github.com/opencollective/opencollective-api/pull/6648
Requirement for https://github.com/opencollective/opencollective-frontend/pull/6931
> Filter transactions by hosted accounts

- .github/workflows/ci.yml
Part of https://github.com/opencollective/opencollective/issues/3171
Require https://github.com/opencollective/opencollective-api/pull/7868
> Remove Postgis extension

- src/graphql/schema.graphql
- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.js
Resolve https://github.com/opencollective/opencollective/issues/6049
[agora-collective-transactions.csv](https://github.com/opencollective/opencollective-rest/files/9923999/agora-collective-transactions.csv)
> Add memo field to transactions csv

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/server/controllers/account-transactions.js
- src/server/index.js
- test/server/api.json.test.js
Requires https://github.com/opencollective/opencollective-api/pull/8727.
> account-transactions cookie support and optimizations

- src/graphql/schema.graphql
- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.js
Resolve https://github.com/opencollective/opencollective/issues/6546
[zgora-collective-transactions(6).csv](https://github.com/opencollective/opencollective-rest/files/10974641/zgora-collective-transactions.6.csv)
> Add Order Processed Date to csv

- src/server/controllers/members.js
Fix for https://opencollective.slack.com/archives/C6JTTA4SK/p1683388259931749
> Set default limit to 1000

- src/server/controllers/events.js
- src/server/lib/graphql.js
- src/server/routes.js
- test/server/api.json.test.js
currently broken and no one complained about
> Deprecate events.json

- src/server/controllers/account-transactions.js
Resolve https://github.com/opencollective/opencollective/issues/7277
> Transactions: Add payment method filter

- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.js
Requires https://github.com/opencollective/opencollective-api/pull/9829
Related to https://github.com/opencollective/opencollective/issues/7210
> Add support for transactions effective date

- package-lock.json
- package.json
- src/server/controllers/account-contributors.js
- src/server/controllers/account-transactions.js
The former package was deprecated and outdated. I updated the source and pushed to the newest version, and everything seems to be working correctly.
> Update source of json2csv package

- src/server/controllers/account-transactions.js
Follow up for https://github.com/opencollective/opencollective-rest/pull/548, missed adding the new args in the query.
> Fix(account-transactions): Include new GraphQL args in query

- src/graphql/schemaV2.graphql
- src/server/controllers/account-contributors.js
oppositeAccount instead of searchTerm
> Update GraphQL syntax to fetch orders

- src/graphql/schemaV2.graphql
- src/server/controllers/hosted-collectives.ts
- src/server/lib/utils.ts
Requires https://github.com/opencollective/opencollective-api/pull/10399
Adds:
- Status
- Date unhosted
- Last freeze end
- Number of expenses last 12 months
- Number of payees all time
- Number of payees last 12 months
- Total host fees collected
- Total raised all time
- Total raised last 12 months
- Total spend all time
- Total spend last 12 months
- Total value of expenses all time
- Total value of expenses last 12 months
- Largest expense value
> Add fields to Hosted Collectives CSV

- src/server/controllers/account-transactions.ts
Resolves https://github.com/opencollective/opencollective/issues/7731
> Account Transactions: include missing clearedAt filters

- src/graphql/schema.graphql
- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.ts
Part of https://github.com/opencollective/opencollective/issues/7774
Require https://github.com/opencollective/opencollective-api/pull/10632
> feat(Transactions): add transactions import fields

- src/server/controllers/account-contributors.js
- src/server/controllers/account-transactions.ts
- src/server/controllers/hosted-collectives.ts
Resolves https://github.com/opencollective/opencollective/issues/7831
> Export Addresses

- src/server/controllers/account-contributors.js
- src/server/controllers/account-transactions.ts
- src/server/controllers/hosted-collectives.ts
Resolves this comment: https://github.com/opencollective/opencollective/issues/7229#issuecomment-1898279579
> enhancement: Return empty CSVs rather than 404s

- src/server/controllers/members.js
Follow-up on https://github.com/opencollective/opencollective-rest/pull/600
> fix(Members): get isActive flag in member

- src/graphql/schema.graphql
- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.ts
Require https://github.com/opencollective/opencollective-api/pull/10799
> feat(TransactionsImport): surface import source name

- src/graphql/schemaV2.graphql
- src/server/controllers/account-transactions.ts
Requires https://github.com/opencollective/opencollective-api/pull/10837
Requires https://github.com/opencollective/opencollective-frontend/pull/11196
> Modified Transactions: Export refund reason and keep track of edited funds
